eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka1
server:
  port: 8761