eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka2
server:
  port: 8762